config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  resources :articles,only: [:show,:index,:new,:create,:edit,:update,:destroy]
  resources :articles
  get 'signup', to:'users#new'
  resources:users, except:[:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article <ApplicationRecord
    belongs_to:user
    validates :title,presence:true,length:{minimum:6,maximum:100}
    validates :description,presence:true,length:{minimum:15,maximum:250}
end

app/models/user.rb
class User < ApplicationRecord
before_save{self.email=email.downcase}
has_many:articles  
validates :username,
        presence:true, 
        uniqueness: { case_sensitive: false },
        length:{minimum:3,maximum:25}
VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email,presence:true,
           uniqueness: { case_sensitive: false },
            length:{maximum:105},
            format:{with:VALID_EMAIL_REGEX}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :article_find, only: [:show,:edit,:update,:destroy]

    def show
    end

    def index
        @articles=Article.all
    end

    def new
        @article=Article.new
    end

    def edit
    end

    def create
        @article=Article.new(article_title_desc)
        @article.user=User.first
       if @article.save
        flash[:notice]="Article was created succesfully."
        redirect_to @article
       else
        render 'new'
       end
    end

    def update
       if @article.update(article_title_desc)
        flash[:notice]="Article was updated successfully."
        redirect_to @article
       else
        render 'edit' 
       end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
      end

    private

    def article_find
        @article = Article.find(params[:id])
    end

    def article_title_desc
        params.require(:article).permit(:title,:description)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController<ApplicationController

    def show
        @user=User.find(params[:id])
        @articles=@user.articles
    end

    def new
        @user=User.new
    end

    def create
        @user=User.new(user_params)
        if @user.save
            flash[:notice]="wellcome to the Alpha Blog #{@user.username}, you have successfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        @user=User.find(params[:id])
    end

    def update
        @user=User.find(params[:id])
        if @user.update(user_params)
            flash[:notice]="Your account information was successfully updated"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    private 
    def user_params
        params.require(:user).permit(:username,:email,:password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user,options={size:80})
        email_address=user.email.downcase
        hash=Digest::MD5.hexdigest(email_address)
        size=options[:size]
        gravatar_url="http://gravatar.com/avatar/#{hash}?s#{size}"
        image_tag(gravatar_url,alt:user.username,class: "rounded shadow mx-auto d-block")
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
    <div class="container">
    <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="container">
            <% @articles.each do |article| %>
                <div class="row justify-content-md-center">
                    <div class="col-8 mt-4 shadow mb-5 bg-body rounded">
                        <div class="card text-center">
                            <div class="card-header font-italic">
                                by <%= article.user.username if article.user%>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <%= link_to article.title, article_path(article),class: "text-success" %>
                                </h5>
                                <p class="card-text">
                                    <%= truncate(article.description,length:100) %>
                                </p>
                                <%= link_to 'Show' , article_path(article), class:"btn btn-outline-success" %>
                                    <%= link_to 'Edit' , edit_article_path(article),class:"btn btn-outline-primary" %>
                                        <%= link_to 'Delete' , article_path(article), data: {
                                            turbo_confirm: "Are you sure?" ,turbo_method: :delete }, class:"btn
                                            btn-outline-danger" %>
                            </div>
                            <div class="card-footer text-muted">
                                <small>Created<%= time_ago_in_words(article.created_at)%> ago,Edited<%=
                                            time_ago_in_words(article.updated_at)%> ago</small>
                            </div>
                        </div>
                    </div>
                </div>
                <%end%>
        </div>
        </div>

app/views/articles/_form.html.erb
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "shared/errors",obj:@article %>
                <%= form_with scope: :article, url:articles_path,local:true do |f| %>
                    <div class="shadow p-3 mb-3 bg-info rounded">
                        <div class="form-group row">
                            <%= f.label :title,class:"col-2 col-form-label text-light" %>
                                <div class="col-10">
                                    <%= f.text_field :title,class:"form-control mb-3 shadow-rounded",placeholder:"Title"
                                        %>
                                </div>
                        </div>

                        <div class=" form-group row">
                            <%= f.label :Description,class:"col-2 col-form-label text-light" %>
                                <div class="col-10">
                                    <%= f.text_area :description,rows:10,class:"form-control mb-3
                                        shadow-rounded",placeholder:"Description of Article" %>
                                </div>
                        </div>

                        <div class="form-group row justify-content-center">
                            <%= f.submit class:"btn btn-outline-light btn-lg" %>
                        </div>
                    </div>
                    <% end %>
        </div>

    </div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create a new article</h1>
    <%= render "form" %>
</div>

app/views/articles/index.html.erb
    <h1 class="text-center mt-4">Listing all articles</h1>
    <%= render 'article' %>
  

app/views/articles/new.html.erb
    <h1 class="text-center mt-4">Create a new article</h1>
    <%= render 'form' %>

app/views/articles/show.html.erb
    <h2 class="text-center mt-4"><%= @article.title %></h2>
    <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-8 mt-4 shadow mb-5 bg-body rounded">
                        <div class="card text-center">
                            <div class="card-header font-italic">
                                by <%= @article.user.username if @article.user%>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <%= link_to @article.title, article_path(@article),class: "text-success" %>
                                </h5>
                                <div class="card-text text-left">
                                    <%= simple_format(@article.description) %></div>
                                </p>
                                    <%= link_to 'Edit' , edit_article_path(@article),class:"btn btn-outline-primary" %>
                                    <%= link_to 'Delete' , article_path(@article), data: {turbo_method: :delete }, class:"btn
                                            btn-outline-danger" %>
                            </div>
                            <div class="card-footer text-muted">
                                <small>Created<%= time_ago_in_words(@article.created_at)%> ago,Edited<%=
                                            time_ago_in_words(@article.updated_at)%> ago</small>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
   

app/views/home/home.html.erb
    <div class="container" id="home-container">
        <div class="bg-light rounded-lg m-3 text-center jumbotron text-white">
            <h1 class="display-4 ">Alpha Blog</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention
                to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <%= link_to "Sign up!", signup_path,class:"btn btn-success btn-lg"%>
        </div>
    </div>

app/views/layouts/_footer.html.erb
    <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy;<%= "Ganesh Devkar" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

      <%= msg %>
      </div

    <% end %>

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG",root_path,class:"navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Create new article", new_article_path, class:"dropdown-item"%>
            <%= link_to "View articles", articles_path, class:"dropdown-item"%>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>alphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track":"reload"%>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 <%= render "layouts/navigation" %>
  <div id="page-content">
 <%= render "layouts/messages"%>
    <%= yield %>
    <%= render "layouts/footer"%>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <h4 class="alert-heading">The Following errors prevented the <%= obj.class.name.downcase%> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <%= msg %>
                    <% end %>
        </ul>
    </div>
    <% end %>

app/views/users/_form.html.erb
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "shared/errors", obj:@user %>
                <%= form_with(model:@user,class:"shadowp-3 mb-3 bg-info rounded",local:true) do |f| %>
                    <div class="shadow p-3 mb-3 bg-info rounded">
                        <div class="form-group row">
                            <%= f.label :Username,class:"col-2 col-form-label text-light" %>
                                <div class="col-10">
                                    <%= f.text_field :username,class:"form-control mb-3 shadow-rounded",placeholder:"Enter a username"
                                        %>
                                </div>
                        </div>

                        <div class=" form-group row mb-3">
                            <%= f.label :Email,class:"col-2 col-form-label text-light" %>
                                <div class="col-10">
                                    <%= f.email_field :email,rows:10,class:"form-control
                                        shadow-rounded",placeholder:"Enter your email address " %>
                                </div>
                        </div>

                          <div class=" form-group row mb-3">
                            <%= f.label :Password,class:"col-2 col-form-label text-light" %>
                                <div class="col-10">
                                    <%= f.password_field :password,rows:10,class:"form-control
                                        shadow-rounded",placeholder:"Choose a password" %>
                                </div>
                        </div>

                        <div class="form-group row justify-content-center">
                            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
                        </div>
                    </div>
                    <% end %>
        </div>

    </div>

app/views/users/edit.html.erb
    <h1 class="text-center mt-4">Edit your profile</h1>
    <%= render 'form' %>

app/views/users/new.html.erb
    <h1 class="text-center mt-4">Signup for Alpha_blog</h1>
    <%= render 'form' %>

app/views/users/show.html.erb
    <h1 class="text-center mt-4"><%= @user.username%>'s profile.</h1>
    <%= gravatar_for @user, size: 200 %>
<h3 class="text-center mt-4">Articles</h3>
<%= render 'articles/article'%>